---
- name: reboot
  ansible.builtin.reboot: 
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 3600
    test_command: uptime 
    pre_reboot_delay: 15
  become: true 

- name: restart sshd 
  ansible.builtin.systemd: 
    name: sshd 
    state: restarted 
  become: true