---
- block:
  - name: Update apt cache 
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Upgrade installed packages
    ansible.builtin.apt:
      upgrade: safe

  - name: Perform dist-upgrade
    ansible.builtin.apt:
      upgrade: dist

  - name: Remove unused packages
    ansible.builtin.apt:
      autoremove: true

  - name: Clean up package cache
    ansible.builtin.apt:
      autoclean: true

- name: Determine if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  changed_when: reboot_required_file.stat.exists
  failed_when: false 
  notify: reboot
  tags: ['never', 'reboot']
