---
- block:
  - name: Update apt cache 
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: Install extra required packages 
    ansible.builtin.package: 
      name: "{{ item }}"
      state: latest 
    loop: "{{ os_baseline_extra_packages }}"
    
  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist
  become: true

- name: Determine if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  changed_when: reboot_required_file.stat.exists
  failed_when: false 
  notify: reboot
  tags: ['never', 'reboot']
