---
- block:
  - name: yum update 
    ansible.builtin.yum: 
      update_cache: true 
      name: "*"
      state: latest 
  
- name: Determine if reboot is required
  ansible.builtin.shell: needs-restarting -r 
  register: reboot_required 
  ignore_errors: true 
  failed_when: false 
  changed_when: reboot_required.rc != 0
  become: true
  notify: reboot 
  tags: ['never', 'reboot']
