---
- name: yum update 
  yum: 
    update_cache: true 
    name: "*"
    state: latest 
  become: true

- name: Install extra required packages 
  ansible.builtin.package: 
    name: "{{ item }}"
    state: latest 
  loop: "{{ os_baseline_extra_packages }}"
  
- name: Determine if reboot is required
  shell: needs-restarting -r 
  register: reboot_required 
  ignore_errors: true 
  failed_when: false 
  changed_when: reboot_required.rc != 0
  become: true
  notify: reboot 
  tags: ['never', 'reboot']
