---
# this is pretty much just for molecule testing
- name: Install openssh
  ansible.builtin.package:
    name: openssh-server 
    state: present
  become: true 

- name: Ensure ssh config dir exists
  ansible.builtin.file:
    name: /etc/ssh 
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true 
  
- name: Update ssh config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  become: true 
  notify: restart sshd

- block: 
  - name: Install policycoreutils-python-utils package (required for semanage)
    ansible.builtin.package:
      name: policycoreutils-python-utils
      state: present

  - name: Check if SSH port {{ os_baseline_sshd_port }} rule exists in SELinux
    ansible.builtin.shell: semanage port -l | grep -P "ssh_port_t.*{{ os_baseline_sshd_port }}"
    register: selinux_ssh_port_check
    failed_when: false
    changed_when: false
    when: 

  - debug: var=selinux_ssh_port_check
    when: debug | default(false) | bool
    
  - name: Add SSH port {{ os_baseline_sshd_port }} rule in SELinux
    ansible.builtin.command: semanage port -a -t ssh_port_t -p tcp {{ os_baseline_sshd_port }}
    when: 
    - selinux_ssh_port_check.rc != 0
  when: 
  - ansible_os_family == 'RedHat'
  - ansible_selinux.status == 'enabled'
  become: true

  # run restart sshd now
- meta: flush_handlers 
