---
on:
  pull_request:
    types:
      - opened
      - synchronize
  schedule:
    - cron: '30 5 * * 0'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: molecule
        uses: robertdebock/molecule-action@5.0.1